supervisor:
  logfile: "/var/log/supervisor.log"
  sigterm_grace_period: 10
  keep_running: "off"
  color: "\e[0;34m" # blue text color

jobs:
  - name: "job1-restart"
    command: "echo 'Job 1: I will fail in 4 seconds. But supervisor will restart me 3 times.'; sleep 4; exit 1"
    autostart: "on"
    restart: "error"

  - name: "job2-no-restart"
    command: "echo 'Job 2: No restart for me on failure in 3 seconds.'; sleep 3; exit 1"
    restart: "off"

  - name: "job3-no-autostart"
    command: "echo 'Job 3: I was started manually'"
    autostart: "off"
    logfile: "/var/log/job4.log"

  - name: "job4-required"
    command: "echo 'Job 4: I am required. When I stop in 20 seconds, supervisor will stop too.'; sleep 20"
    restart: "off"
    required: "yes"

  - name: "job5-ignore-SIGTERM"
    command: "trap true SIGTERM; echo 'Job 5: I will ignore SIGTERM.'; while :; do sleep 1d; done"
